//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using SQLite;
using System;

namespace LegendaryData.Models
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<Henchmen>();
                db.CreateTable<Heroes>();
                db.CreateTable<Masterminds>();
                db.CreateTable<Settings>();
                db.CreateTable<Stat_Affiliation>();
                db.CreateTable<Stat_Author>();
                db.CreateTable<VillainGroups>();
            }
        }
    }
    public partial class Henchmen
    {
        [PrimaryKey, AutoIncrement]
        public Int64 ID { get; set; }
        
        [MaxLength(254)]
        public String HenchmenName { get; set; }
        
        [MaxLength(254)]
        public String BGGLink { get; set; }
        
        [MaxLength(254)]
        public String Author { get; set; }
        
        [MaxLength(254)]
        public String ExpansionName { get; set; }
        
        [MaxLength(254)]
        public String UniverseName { get; set; }
        
        [MaxLength(254)]
        public String Year { get; set; }
        
    }
    
    public partial class Heroes
    {
        [PrimaryKey, AutoIncrement]
        public Int64 ID { get; set; }
        
        [MaxLength(75)]
        [NotNull]
        public String HeroName { get; set; }
        
        [MaxLength(254)]
        public String BGGLink { get; set; }
        
        [MaxLength(50)]
        public String Author { get; set; }
        
        [MaxLength(50)]
        public String ExpansionName { get; set; }
        
        [MaxLength(50)]
        public String Universe { get; set; }
        
        [MaxLength(10)]
        public String Year { get; set; }
        
        [MaxLength(254)]
        public String TeamName { get; set; }
        
        public Boolean? IsOfficial { get; set; }
        
        [MaxLength(254)]
        public String Key { get; set; }
        
    }
    
    public partial class Masterminds
    {
        [PrimaryKey, AutoIncrement]
        public Int64 ID { get; set; }
        
        [MaxLength(254)]
        [NotNull]
        public String MastermindName { get; set; }
        
        [MaxLength(254)]
        public String BGGLink { get; set; }
        
        [MaxLength(254)]
        public String Author { get; set; }
        
        [MaxLength(254)]
        public String ExpansionName { get; set; }
        
        [MaxLength(254)]
        public String UniverseName { get; set; }
        
        [MaxLength(254)]
        public String Year { get; set; }
        
        [MaxLength(254)]
        public String Key { get; set; }
        
    }
    
    public partial class Settings
    {
        [PrimaryKey, AutoIncrement]
        public Int64 ID { get; set; }
        
        [MaxLength(254)]
        [NotNull]
        public String SettingName { get; set; }
        
        public String SettingValue { get; set; }
        
    }
    
    public partial class Stat_Affiliation
    {
        [PrimaryKey, AutoIncrement]
        public Int64 ID { get; set; }
        
        [MaxLength(254)]
        [NotNull]
        public String TeamName { get; set; }
        
        [MaxLength(254)]
        public String UniverseName { get; set; }
        
    }
    
    public partial class Stat_Author
    {
        [PrimaryKey, AutoIncrement]
        public Int64 ID { get; set; }
        
        [MaxLength(254)]
        [NotNull]
        public String AuthorName { get; set; }
        
        [MaxLength(254)]
        public String BGGLink { get; set; }
        
    }
    
    public partial class VillainGroups
    {
        [PrimaryKey, AutoIncrement]
        public Int64 ID { get; set; }
        
        [MaxLength(254)]
        public String VillainGroup { get; set; }
        
        [MaxLength(254)]
        public String BGGLink { get; set; }
        
        [MaxLength(254)]
        public String Author { get; set; }
        
        [MaxLength(254)]
        public String ExpansionName { get; set; }
        
        [MaxLength(254)]
        public String UniverseName { get; set; }
        
        [MaxLength(254)]
        public String Year { get; set; }
        
    }
    
}
